### ISSUE TITLE
Bypass Low Target SDK Block isn't appearing

### ISSUE THREAD

**Issue by NikunjKhangwal** [zacharee/InstallWithOptions#13]
Exactly the title. For some reason this option isn't appearing in the app. I've tried older versions as well. I'm using magisk root to grant access.

**Comment by zacharee** [comment]
Are you on Android 14?

**Comment by NikunjKhangwal** [comment]
Android 12

**Comment by zacharee** [comment]
The low target SDK block was only introduced in Android 14, so it's not going to show up in the app below that.

**Comment by NikunjKhangwal** [comment]
> The low target SDK block was only introduced in Android 14, so it's not going to show up in the app below that.

There are still restrictions in Android versions below 14. You can't install many old apks. Is there any way around that?

**Comment by zacharee** [comment]
Which APKs can't you install?

**Comment by NikunjKhangwal** [comment]
Can't remember now, it happened a while back. What I'm referring to is, some outdated apps doesn't target the new android versions. Is there any way to implement something like this app automatically bump sdk of selected apks to match the device so compatibility issues can be minimized?

**Comment by kanking** [comment]
I agree. Should allow that option for all not just 14

**Comment by zacharee** [comment]
It doesn't exist below Android 14.

**Comment by NikunjKhangwal** [comment]
> It doesn't exist below Android 14.

Is the feature i mentioned (making apk match sdk of device) or something similar? If it's not that's fine too, I'll be closing the issue.

**Comment by zacharee** [comment]
That would involve decompiling the APK and recompiling it, and would also probably break the app. The target SDK isn't just a number, it has major behavior and security changes associated with it.

**Comment by NikunjKhangwal** [comment]
Alright, fair enough. Thanks for the response
