### ISSUE TITLE
Loading infinitely, not installing

### ISSUE THREAD

**Issue by Ketsuyumi** [zacharee/InstallWithOptions#16]
![Screenshot_20240330_181113_Install with Options](https://github.com/zacharee/InstallWithOptions/assets/98485150/1fed18c1-c925-4dac-a1eb-7fd25781b7db)

**Comment by Gadgetonomy** [comment]
Same issue (Galaxy S24 Ultra)

**Comment by Mehmetfit** [comment]
Same issue S24 Ultra

**Comment by zacharee** [comment]
This should be fixed in 0.4.2
