### ISSUE TITLE
App keeps stop

### ISSUE THREAD

**Issue by DivineXLight** [zacharee/InstallWithOptions#17]
I'm using Shizuku instead of rooting my phone. App still keeps stopping. Any suggestions?

**Comment by swiftness427** [comment]
Pair it with a code to your phone and it won't keep stopping. The latest
release of SD Maid you should use the version
https://github.com/d4rken-org/sdmaid-se

**Comment by DivineXLight** [comment]
Alr, I got the app. Could you explain what I should do more thoroughly? I'm kinda confused. Ty.

**Comment by DivineXLight** [comment]
Alr I've did all that. But what should I do with install with options now?

**Comment by swiftness427** [comment]
This is the setup guide

https://github.com/d4rken-org/sdmaid-se/wiki/Setup






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
