### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by wr3cckl3ss** [zacharee/InstallWithOptions#18]
I might be shooting for the moon here but I wanna ask and see if maybe a little command line box could be implemented with a text view for logging. Besides having the ability to already check on and off the install arguments for what we may want to use, I think having something like what Hail has would be extremely beneficial. Not to say that the options here are not enough or they lack any specialty but, I do see the opportunity for advancement, as far as installing apks. But I'll leave it at that. And will elaborate later. More importantly it's the ability to just add specific arguments on the go. For example, like "-r" "-d" ![Screenshot_20240407_230235_Hail.jpg](https://github.com/zacharee/InstallWithOptions/assets/97212092/1f5c585c-5499-4ed1-9c3c-a0ff2b6bbb17)

**Comment by zacharee** [comment]
Since I'm using the Java API for installing APKs, I can't really provide a freeform input. There also aren't any logs to show except the final success/failure status.
