### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Russe098** [zacharee/InstallWithOptions#27]
While installing the app, enable the feature to install the app completely to the external storage, because this feature is very useful, please help us by adding the feature.

(External"
Force the package to be installed to external storage)

![20240509-222646](https://github.com/zacharee/InstallWithOptions/assets/146573141/1a7d86c4-7cfc-4d47-ad44-edaec8ddc5e0)

**Comment by zacharee** [comment]
Force installing on external storage was removed as a flag after Android 9.
