### ISSUE TITLE
INSTALL_FAILED_USER_RESTRICTED

### ISSUE THREAD

**Issue by Mufidhalal** [zacharee/InstallWithOptions#42]
This is my brothers Phone and he wanted to download Trainz Simulator, And The Error Pops Ups When Bypassing Target SDK Block

**Comment by Mufidhalal** [comment]
![Uploading 17207490667356480131582331898161.jpg…]()

**Comment by zacharee** [comment]
This error means you aren't allowed to install apps. This could be because of parental controls, a work/company policy, or another restriction on your device. It isn't something Install With Options can address.
