### ISSUE TITLE
Requesting Installer

### ISSUE THREAD

**Issue by wr3cckl3ss** [zacharee/InstallWithOptions#5]
Mr. Z, I humbly request at your earliest convenience, if can you implement an installer like those of Bugjaeager. It makes purposeful use of the -i argument when installing apps. For instance using the commands of,

pm install -i PrePackageInstaller (path to APK)
or
pm install -i com.sec.android.preloadinstaller (path to APK)

😉🤣😉🤣

**Comment by drogga** [comment]
You should probably tag/mention the owner to draw their attention to this, which if it does have that, then it will be better than InstallerX.

**Comment by wr3cckl3ss** [comment]
It's not needed as this was just a reminder to the developer to the dev for my request. And I want to say that yes it would be 10 times better than that of Installer X. But me personally don't need all the script kiddies to go crazy trying every installer possible especially on Samsung devices 😁🤣😉.  If this was my project I would probably have a special branch that would implement this but also prevent the masses from trying to take advantage of a tool that could be very useful depending on what you do. I would most definitely keep it separate as well but this is not my project and I only made a mere recommendation. Haven't got a response yet so I hope, he approves.

**Comment by zacharee** [comment]
Added in 0.4.0.
