### ISSUE TITLE
VERSION MISMATCH 

### ISSUE THREAD

**Issue by paaavannn7** [zacharee/InstallWithOptions#55]
I have disabled verification still I get this error

![Screenshot_20240911-134803_Install with Options](https://github.com/user-attachments/assets/ac2b3145-a0bb-4fcd-aca2-08a7f519cf37)

**Comment by drogga** [comment]
It's so obvious, someone just has to read (option description & the error text, especially the last words)...

**Comment by paaavannn7** [comment]
> It's so obvious, someone just has to read (option description & the error text, especially the last words)...

yeah that's why I need to use this app, to bypass all the verification and just install it.

**Comment by drogga** [comment]
You can't without root and xposed/magisk/lsposed and a module or a patched core/framework.jar, Lucky Patcher can do this. It's clearly mentioned in the option's description that this is not the same as signature/certificate verification, which is the thing you are facing, either make a clean install, or you will have to use other tools for this, as I mentioned above.

**Comment by paaavannn7** [comment]
I am rooted, using lsposed, magisk. I will look into it.
