### ISSUE TITLE
Bypass Low Target SDK Block

### ISSUE THREAD

**Issue by OPK1NGF1SH** [zacharee/InstallWithOptions#63]
Please help ![Screenshot_2024-10-20-16-41-24-596_dev.zwander.installwithoptions-edit.jpg](https://github.com/user-attachments/assets/814006ad-a702-4c62-a1c0-ba4b1e46418e)

**Comment by drogga** [comment]
Read the comments in #22 & #47

**Comment by drogga** [comment]
@zacharee should it state/repeat the same line twice ?

**Comment by zacharee** [comment]
This is addressed in the readme: https://github.com/zacharee/InstallWithOptions/?tab=readme-ov-file#install_failed_no_matching_abis.

@drogga the dialog just shows what the system returned, so if it's doubled, that means Android doubled it.
