### ISSUE TITLE
Restricted Permissions

### ISSUE THREAD

**Issue by PeterKW** [zacharee/InstallWithOptions#7]
Sorry for the possible silly question but I'm a bit confused by this. Would this install the application as an admin level application?

**Comment by drogga** [comment]
No.

**Comment by PeterKW** [comment]
> No.

What are restricted permissions?

**Comment by drogga** [comment]
Permissions that are usually restricted.
...I'm not sure what are you asking exactly, please elaborate (with context)...

**Comment by zacharee** [comment]
Restricted permissions were introduced in Android 12, and it's a concept that applies to existing permissions, not new ones. For example, sideloading an application will prevent you from enabling its Accessibility Service (if it has one) until you go to the App Info in Settings, tap the three-dot menu, and confirm your screen lock.
